version: '3'

networks:
  dynet:

services: 
  server0:
    container_name: server0
    image: server:latest
    privileged: true
    working_dir: /home/dy/server
    command: ./main N0
      # - /bin/sh
      # - -c
      # - |
      #   cd /home/dy/server
      #   tc qdisc add dev eth0 root netem delay $DELAY $JITTER rate $RATE
      #   ./main N0
    volumes: 
      - ../experiment/server0/store:/home/dy/server/store
      - ../experiment/server0/Keys:/home/dy/server/Keys
      - ../experiment/server0/log:/home/dy/server/log
    # ports: 
    
    networks: 
      - dynet

  server1:
    container_name: server1
    image: server:latest
    privileged: true
    working_dir: /home/dy/server
    command: 
      - /bin/sh
      - -c
      - |
        cd /home/dy/server
        tc qdisc add dev eth0 root netem delay $DELAY $JITTER
        ./main N1
    volumes: 
      - ../experiment/server1/store:/home/dy/server/store
      - ../experiment/server1/Keys:/home/dy/server/Keys
    # ports: 
    
    networks: 
      - dynet

  server2:
    container_name: server2
    image: server:latest
    privileged: true
    working_dir: /home/dy/server
    command: 
      - /bin/sh
      - -c
      - |
        cd /home/dy/server
        tc qdisc add dev eth0 root netem delay $DELAY $JITTER
        ./main N2
    volumes: 
      - ../experiment/server2/store:/home/dy/server/store
      - ../experiment/server2/Keys:/home/dy/server/Keys
    # ports: 
    
    networks: 
      - dynet
  
  server3:
    container_name: server3
    image: server:latest
    privileged: true
    working_dir: /home/dy/server
    command: 
      - /bin/sh
      - -c
      - |
        cd /home/dy/server
        tc qdisc add dev eth0 root netem delay $DELAY $JITTER
        ./main N3
    volumes: 
      - ../experiment/server3/store:/home/dy/server/store
      - ../experiment/server3/Keys:/home/dy/server/Keys
    # ports: 
    
    networks: 
      - dynet

  # server4:
  #   container_name: server4
  #   image: server:latest
  #   privileged: true
  #   working_dir: /home/dy/server
  #   command: 
  #     - /bin/sh
  #     - -c
  #     - |
  #       cd /home/dy/server
  #       tc qdisc add dev eth0 root netem delay $DELAY $JITTER
  #       ./main N4
  #   volumes: 
  #     - ../experiment/server4/store:/home/dy/server/store
  #     - ../experiment/server4/Keys:/home/dy/server/Keys
  #   # ports: 
    
  #   networks: 
  #     - dynet

  # server5:
  #   container_name: server5
  #   image: server:latest
  #   privileged: true
  #   working_dir: /home/dy/server
  #   command: 
  #     - /bin/sh
  #     - -c
  #     - |
  #       cd /home/dy/server
  #       tc qdisc add dev eth0 root netem delay $DELAY $JITTER
  #       ./main N5
  #   volumes: 
  #     - ../experiment/server5/store:/home/dy/server/store
  #     - ../experiment/server5/Keys:/home/dy/server/Keys
  #   # ports: 
    
  #   networks: 
  #     - dynet

  # server6:
  #   container_name: server6
  #   image: server:latest
  #   privileged: true
  #   working_dir: /home/dy/server
  #   command: 
  #     - /bin/sh
  #     - -c
  #     - |
  #       cd /home/dy/server
  #       tc qdisc add dev eth0 root netem delay $DELAY $JITTER
  #       ./main N6
  #   volumes: 
  #     - ../experiment/server6/store:/home/dy/server/store
  #     - ../experiment/server6/Keys:/home/dy/server/Keys
  #   # ports: 
    
  #   networks: 
  #     - dynet

  # server7:
  #   container_name: server7
  #   image: server:latest
  #   privileged: true
  #   working_dir: /home/dy/server
  #   command: 
  #     - /bin/sh
  #     - -c
  #     - |
  #       cd /home/dy/server
  #       tc qdisc add dev eth0 root netem delay $DELAY $JITTER
  #       ./main N7
  #   volumes: 
  #     - ../experiment/server7/store:/home/dy/server/store
  #     - ../experiment/server7/Keys:/home/dy/server/Keys
  #   # ports: 
    
  #   networks: 
  #     - dynet

  # server8:
  #   container_name: server8
  #   image: server:latest
  #   privileged: true
  #   working_dir: /home/dy/server
  #   command: 
  #     - /bin/sh
  #     - -c
  #     - |
  #       cd /home/dy/server
  #       tc qdisc add dev eth0 root netem delay $DELAY $JITTER
  #       ./main N8
  #   volumes: 
  #     - ../experiment/server8/store:/home/dy/server/store
  #     - ../experiment/server8/Keys:/home/dy/server/Keys
  #   # ports: 
    
  #   networks: 
  #     - dynet

  # server9:
  #   container_name: server9
  #   image: server:latest
  #   privileged: true
  #   working_dir: /home/dy/server
  #   command: 
  #     - /bin/sh
  #     - -c
  #     - |
  #       cd /home/dy/server
  #       tc qdisc add dev eth0 root netem delay $DELAY $JITTER
  #       ./main N9
  #   volumes: 
  #     - ../experiment/server9/store:/home/dy/server/store
  #     - ../experiment/server9/Keys:/home/dy/server/Keys
  #   # ports: 
    
  #   networks: 
  #     - dynet